sudo: required
services:
  - docker

before_install:
  - docker build -t medsaidraoudh/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run  -e CI=true medsaidraoudh/react-test npm test -- --coverage

after_success:
  - docker build -t medsaidraoudh/multi-client ./client
  - docker build -t medsaidraoudh/multi-nginx ./nginx
  - docker build -t medsaidraoudh/multi-server ./server
  - docker build -t medsaidraoudh/multi-worker ./worker
  #log in to the docker cli
  - echo "$docker_password" | docker login -u "$docker_id" --password-stdin
  # take those images and push 
  - docker push medsaidraoudh/multi-client 
  - docker push medsaidraoudh/multi-nginx 
  - docker push medsaidraoudh/multi-server 
  - docker push medsaidraoudh/multi-worker 
